version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-4.7"
  jobs:
    pre_build:
      - mkdir docs/source/_static
      - rm -Rf docs/source/notebooks
      - cp -R notebooks docs/source

conda:
  environment: docs/docs_env.yml

sphinx:
  builder: html
  fail_on_warning: false
  configuration: docs/source/conf.py